import java.sql.*;
import java.time.LocalDateTime;
import java.io.BufferedReader;
import java.io.InputStreamReader;

public class CloudMonitor {

	    static final String DB_URL = "jdbc:mariadb://localhost:3306/cloud_monitor";
	        static final String USER = "clouduser";
		    static final String PASSWORD = "Cloud@1234";

		        public static void main(String[] args) {

				        try {
						            Class.forName("org.mariadb.jdbc.Driver");

							                Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD);

									            // run 10 times; //(safe for testing);
										                 for (int i = 0; i < 10; i++) {
										    
										                                 String cpu = getCPUUsage();
										                                                 String memory = getMemoryUsage();
										                                                                 int processes = getProcessCount();
										    
										                                                                                 Timestamp timestamp = Timestamp.valueOf(LocalDateTime.now());
										    
										                                                                                                 String sql = "INSERT INTO system_metrics (cpu_usage, memory_usage, process_count, timestamp) VALUES (?, ?, ?, ?)";
										    
										                                                                                                                 PreparedStatement stmt = conn.prepareStatement(sql);
										    
										                                                                                                                                 stmt.setString(1, cpu);
										                                                                                                                                                 stmt.setString(2, memory);
										                                                                                                                                                                 stmt.setInt(3, processes);
										                                                                                                                                                                                 stmt.setTimestamp(4, timestamp);
										    
										                                                                                                                                                                                                 stmt.executeUpdate();
										    
										                                                                                                                                                                                                                 System.out.println("----------------------------");
										                                                                                                                                                                                                                                 System.out.println("Inserted at: " + timestamp);
										                                                                                                                                                                                                                                                 System.out.println("CPU: " + cpu);
										                                                                                                                                                                                                                                                                 System.out.println("Memory: " + memory);
										                                                                                                                                                                                                                                                                                 System.out.println("Processes: " + processes);
										    
										                                                                                                                                                                                                                                                                                                 Thread.sleep(10000); // 10 sec
										                                                                                                                                                                                                                                                                                                             }
										    
										                                                                                                                                                                                                                                                                                                                         conn.close();
										    
										                                                                                                                                                                                                                                                                                                                                 } catch (Exception e) {
										                                                                                                                                                                                                                                                                                                                                             e.printStackTrace();
										                                                                                                                                                                                                                                                                                                                                                     }
										                                                                                                                                                                                                                                                                                                                                                         }
										    
										                                                                                                                                                                                                                                                                                                                                                             // CPU Usage
										                                                                                                                                                                                                                                                                                                                                                                 public static String getCPUUsage() {
										                                                                                                                                                                                                                                                                                                                                                                         try {
										                                                                                                                                                                                                                                                                                                                                                                                     Process p = Runtime.getRuntime().exec(
										                                                                                                                                                                                                                                                                                                                                                                                                     new String[]{"bash","-c","top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'"}
										                                                                                                                                                                                                                                                                                                                                                                                                                 );
										                                                                                                                                                                                                                                                                                                                                                                                                                             BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
										                                                                                                                                                                                                                                                                                                                                                                                                                                         return br.readLine();
										                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (Exception e) {
										                                                                                                                                                                                                                                                                                                                                                                                                                                                             return "0";
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
										    
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Memory Usage
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 public static String getMemoryUsage() {
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         try {
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Process p = Runtime.getRuntime().exec(
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     new String[]{"bash","-c","free -m | awk 'NR==2{printf \"%s/%s MB\", $3,$2 }'"}
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return br.readLine();
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (Exception e) {
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return "0";
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
										    
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Process Count
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 public static int getProcessCount() {
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         try {
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Process p = Runtime.getRuntime().exec(
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     new String[]{"bash","-c","ps -e --no-headers | wc -l"}
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return Integer.parseInt(br.readLine().trim());
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (Exception e) {
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return 0;
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
										                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
